# Starter pipeline
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-input=false -var="spn-client-id=$(AzDevOps-Client-ID)" -var="spn-client-secret=$(AzDevOps-Client-Secret)"'
    environmentServiceNameAzureRM: 'ES-CE-CUS-EXT-Pajohnst-Management(b7190f8a-860a-428c-a303-7231b1eb2f60)'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
