# Starter pipeline
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'ES-CE-CUS-EXT-Pajohnst-Management(b7190f8a-860a-428c-a303-7231b1eb2f60)'
    backendAzureRmResourceGroupName: 'AzureDevOps'
    backendAzureRmStorageAccountName: 'pjazdevopsdemostg001'
    backendAzureRmContainerName: 'es-azurelab-tf-state'
    backendAzureRmKey: 't+OOsNpYiiVyytJ0ENXV1wGS2cqSwCF3a7xTujJK78C3tsOJp7qW/BugS4ec/Ne2uOGuCR6Ex1fdm7psE4ABkg=='
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'validate'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
